from __future__ import annotations

from typing import Protocol, Any


class MetadataIndex(Protocol):
    def upsert(self, records: list[dict[str, Any]]) -> dict[str, Any]: ...
    def search(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...


class LexicalIndex(Protocol):
    def upsert_spans(self, spans: list[dict[str, Any]]) -> dict[str, Any]: ...
    def search(self, query: str, filters: dict[str, Any]) -> list[dict[str, Any]]: ...


class DocumentTreeIndex(Protocol):
    def upsert_nodes(self, nodes: list[dict[str, Any]]) -> dict[str, Any]: ...
    def traverse(self, node_ref: str) -> list[dict[str, Any]]: ...


class VectorIndex(Protocol):
    def upsert_spans(self, spans: list[dict[str, Any]]) -> dict[str, Any]: ...
    def search(self, query: str, filters: dict[str, Any]) -> list[dict[str, Any]]: ...


class GraphIndex(Protocol):
    def upsert_edges(self, edges: list[dict[str, Any]]) -> dict[str, Any]: ...
    def neighborhood(self, node_ref: str, depth: int = 1) -> list[dict[str, Any]]: ...


class BundleStore(Protocol):
    def put(self, bundle: dict[str, Any]) -> dict[str, Any]: ...
    def get(self, bundle_id: str) -> dict[str, Any] | None: ...
